starfield: starfield.cpp
	g++ starfield.cpp -ostarfield -std=c++11 -ggdb -lsfml-graphics -lsfml-window -lsfml-system

starfield2: starfield2.cpp
	g++ starfield2.cpp -ostarfield2 -std=c++11 -ggdb -lsfml-graphics -lsfml-window -lsfml-system

starfield3: starfield3.cpp
	g++ starfield3.cpp -ostarfield3 -std=c++11 -ggdb -lsfml-graphics -lsfml-window -lsfml-system
