graviton: graviton.cpp Game.h Interface.h Fundament.h Const.h Bullet.h Planet.h Player.h Enemy.h Camera.h Animation.h Board.h Collectable.h
	g++ graviton.cpp -ograviton -std=c++11 -ggdb -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system
